# Generated by Django 2.2.7 on 2019-11-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
        migrations.AddField(
            model_name='store',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
