# Generated by Django 2.2.7 on 2019-11-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191117_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='menu_id',
        ),
    ]
