# Generated by Django 2.2.7 on 2019-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_store_menu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('menu_name', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
