# Generated by Django 2.2.7 on 2019-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
