# Generated by Django 2.2.7 on 2019-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_store_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
