# Generated by Django 2.2.7 on 2019-11-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderList',
        ),
    ]
