# Generated by Django 2.2.7 on 2019-11-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20191121_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderList',
            new_name='Orders',
        ),
    ]
