# Generated by Django 2.2.7 on 2019-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20191121_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
