# Generated by Django 2.2.7 on 2019-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_orders_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='finished',
            new_name='isfinished',
        ),
    ]
