# Generated by Django 2.2.7 on 2019-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20191121_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='isfinished',
            new_name='isFinished',
        ),
    ]
